name: "Install KaaS"
description: "Install KaaS on the Runner for use in later steps and utilize kaas-cli push/pull of KCFGs"
inputs:
  github-token:
    description: "The GitHub Token to use for the checkout of the KaaS repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install Python3.10 or Greater"
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: "Checkout KaaS"
      uses: actions/checkout@v4
      with:
        repository: "runtimeverification/kaas"
        ref: "develop"
        path: "kaas"
        token: ${{ event.inputs.github-token }}

    - name: "Install Pip Packages"
      shell: bash
      run: |
        pip install poetry 
        pip install kaas/kaas-cli/dist/*.whl

    - name: "Install KaaS"
      shell: bash
      run: |
        pushd kaas/kaas-cli/
        make build
        pip install dist/*.whl
        poetry install
        popd

    - name: "Put kaas-cli on the GITHUB_PATH"
      shell: bash
      run: |
        echo "export PATH=\$PATH:\$HOME/.local/bin" >> $GITHUB_PATH