---
name: "Test Installation of KaaS-CLI"
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  install-test:
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use KaaS Action
        uses: ./ 
        with:
          github-token: ${{ secrets.JENKINS_GITHUB_PAT }}

      - name: Test kaas-cli
        shell: bash
        run: |
          kaas-cli